version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf
      - ./site:/var/www/pbaldaray.com
      - ./live/conf:/etc/letsencrypt
      - ./live/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./live/conf:/etc/letsencrypt
      - ./live/www:/var/www/certbot
