#!/bin/bash
function PANIC { echo "$@"; exit 1; }

[ $EUID -ne 0 ] && PANIC "Error: must be run as root"
hash docker || PANIC "Error: docker must be installed"
hash docker-compose || PANIC "Error: docker compose must be installed"

rm -r live

./scripts/setup-placeholders
./scripts/setup-real-certificates
./scripts/update-pages

docker-compose up -d nginx
