#!/bin/bash
domain="pbaldaray.com"
email="paulbaldaray@gmail.com"

echo "Starting nginx ..."
docker-compose up --force-recreate -d nginx

echo "Deleting placeholder certificate for $domain ..."
docker-compose run --rm --entrypoint "\
  rm -Rf /etc/letsencrypt/live/$domain && \
  rm -Rf /etc/letsencrypt/archive/$domain && \
  rm -Rf /etc/letsencrypt/renewal/$domain.conf" certbot

echo "Requesting Let's Encrypt certificate for $domain ..."
docker-compose run --rm --entrypoint "\
	certbot certonly --webroot -w /var/www/certbot \
	--email $email
	-d $domain -d www.$domain \
	--rsa-key-size 4096 \
	--agree-tos \
	--force-renewal" certbot

echo "Reloading nginx ..."
docker-compose exec nginx nginx -s reload
