#!/bin/bash
read -p 'Login? (y/n) ' credentials
if [ "$credentials" = y ]; then
	read -p 'Username: ' username
	read -s -p 'Password: ' password
	login="$username:$password@"
	location="https://$login""github.com/paulbaldaray"
else
	location="https://github.com/paulbaldaray"
fi
function update() {
	[ "$#" -ne 1 ] && echo 'update: invalid args' && exit 1
	if [ ! -e "./site/$1" ]; then
		git clone "$location/$1" "./site/$1"
	else
		cd "./site/$1" && git pull origin master && cd -
	fi
}

update type-type
update chess-simulator

if [ "$credentials" = y ]; then
	update resume
fi
