#!/bin/bash
read -p 'Login? (y/n) ' credentials
if [ "$credentials" = y ]; then
	read -p 'Username: ' username
	read -s -p 'Password: ' password
	login="$username:$password@"
	location="https://$login""github.com/paulbaldaray"
else
	location="https://github.com/paulbaldaray"
fi
dir="./live/repos"
mkdir -p $dir
function update() {
	[ "$#" -ne 1 ] && echo 'update: invalid args' && exit 1
	if [ ! -e "$dir/$1/.git" ]; then
		[ -e "$dir/$1" ] && rm -r "$dir/$1"
		git clone "$location/$1" "$dir/$1"
	else
		cd "$dir/$1" && git pull origin master && cd -
	fi
}

if [ "$credentials" = y ]; then
	update resume
fi

update type-type
update chess-simulator
