#!/bin/bash
read -p 'Login? (y/n) ' credentials
read -p 'Username: ' username
read -p 'Password: ' password
login="$username:$password@"
if [ "$credentials" = y ]; then
	location="https://$login""github.com/$username"
else
	location="https://github.com/$username"
fi
function update() {
	[ "$#" -ne 1 ] && echo 'update: invalid args' && exit 1
	if [ ! -e "site/$1" ]; then
		git clone "$location/$1" ./site/$1
	else
		git pull "$location/$1" ./site/$1
	fi
}
update type-type
update chess-simulator
[ "$credentials" = y ] && update resume
